### PR TITLE
Merge pull request #8 from ajeetvarma/master

### PR DESCRIPTION
**Pull request by ajeetvarma**
Common Pull Problem

### CODE REVIEW

**Comment by dineshsaxena** [comment]
Hi,
Task Completed

**Comment by dineshsaxena** [comment]
Hi,
Did you get any notification

**Comment by dineshsaxena** [comment]
Pleae check the notification

**Comment by dineshsaxena** [comment]
new commit on read me required

**Comment by ajeetvarma** [comment]
well code

**Pull request merged**
